(define (make-point x y) (cons x y))
(define (x-point point) (car point))
(define (y-point point) (cdr point))
(define (raw-print-point point)
    (display "(")
    (display (x-point point))
    (display ", ")
    (display (y-point point))
    (display ")"))
(define (print-point point)
    (newline)
    (raw-print-point point))

(define (make-segment start end) (cons start end))
(define (start-segment segment) (car segment))
(define (end-segment segment) (cdr segment))
(define (print-segment segment)
    (newline)
    (raw-print-point (start-segment segment))
    (display ", ")
    (raw-print-point (end-segment segment)))
(define (midpoint-segment segment)
    (make-point (/ (+ (x-point (start-segment segment))
                      (x-point (end-segment segment)))
                    2)
                (/ (+ (y-point (start-segment segment))
                      (y-point (end-segment segment)))
                    2)))

(define p1 (make-point 1 3))
(define p2 (make-point 5 9))
(define segment (make-segment p1 p2))

(print-point (midpoint-segment segment))
