(define *op-table* (make-hash-table))
(define (put op type proc)
    (hash-table/put! *op-table* (list op type) proc))
(define (get op type)
    (hash-table/get *op-table* (list op type) false))

(define *coercion-table* (make-hash-table))
(define (put-coercion from to coercion)
    (hash-table/put! *coercion-table* (list from to) coercion))
(define (get-coercion from to)
    (hash-table/get *coercion-table* (list from to) false))

(define (attach-tag type-tag contents)
    (if (number? contents)
        contents
        (cons type-tag contents)))
(define (type-tag datum)
    (cond ((pair? datum) (car datum))
          ((exact-integer? datum) 'integer)
          ((real? datum) 'real)
          (else (error "Некорректные помеченные данные -- TYPE-TAG" datum))))
(define (contents datum)
    (cond ((pair? datum) (cdr datum))
          ((number? datum) datum)
          (else (error "Некорректные помеченные данные -- CONTENTS" datum))))

(define (add x y) (apply-generic 'add x y))
(define (add3 x y z) (apply-generic 'add3 x y z))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (exp x y) (apply-generic 'exp x y))
(define (equ? x y) (apply-generic 'equ? x y))
(define (=zero? x) (apply-generic '=zero? x))

; Scheme numbers package
(define (install-integer-package)
    (define (tag x) (attach-tag 'integer x))
    (put 'add '(integer integer) (lambda (x y) (tag (+ x y))))
    (put 'add3 '(integer integer integer) (lambda (x y z) (tag (+ x y z))))
    (put 'sub '(integer integer) (lambda (x y) (tag (- x y))))
    (put 'mul '(integer integer) (lambda (x y) (tag (* x y))))
    (put 'div '(integer integer) (lambda (x y) (tag (/ x y))))
    (put 'exp '(integer integer) (lambda (x y) (tag (expt x y))))
    (put 'equ? '(integer integer) (lambda (x y) (= x y)))
    (put '=zero? '(integer) (lambda (x) (= x 0)))
    (put 'make 'integer (lambda (x) (tag x)))
    'done)
(define (make-integer n)
    ((get 'make 'integer) n))

; Scheme reals package
(define (install-real-package)
    (define (tag x) (attach-tag 'real x))
    (put 'add '(real real) (lambda (x y) (tag (+ x y))))
    (put 'add3 '(real real real) (lambda (x y z) (tag (+ x y z))))
    (put 'sub '(real real) (lambda (x y) (tag (- x y))))
    (put 'mul '(real real) (lambda (x y) (tag (* x y))))
    (put 'div '(real real) (lambda (x y) (tag (/ x y))))
    (put 'exp '(real real) (lambda (x y) (tag (expt x y))))
    (put 'equ? '(real real) (lambda (x y) (= x y)))
    (put '=zero? '(real) (lambda (x) (= x 0)))
    (put 'make 'real (lambda (x) (tag (* x 1.0))))
    'done)
(define (make-real n)
    ((get 'make 'real) n))

; Rational number package
(define (install-rational-package)
    (define (numer x) (car x))
    (define (denom x) (cdr x))
    (define (make-rat n d)
        (let ((g (gcd n d)))
             (cons (/ n g) (/ d g))))
    (define (add-rat x y)
        (make-rat (+ (* (numer x) (denom y))
                     (* (numer y) (denom x)))
                  (* (denom x) (denom y))))
    (define (sub-rat x y)
        (make-rat (- (* (numer x) (denom y))
                     (* (numer y) (denom x)))
                  (* (denom x) (denom y))))
    (define (mul-rat x y)
        (make-rat (* (numer x) (numer y))
                  (* (denom x) (denom y))))
    (define (div-rat x y)
        (make-rat (* (numer x) (denom y))
                  (* (denom x) (numer y))))

    (define (tag x) (attach-tag 'rational x))
    (put 'numer '(rational) numer)
    (put 'denom '(rational) denom)
    (put 'add '(rational rational) (lambda (x y) (tag (add-rat x y))))
    (put 'sub '(rational rational) (lambda (x y) (tag (sub-rat x y))))
    (put 'mul '(rational rational) (lambda (x y) (tag (mul-rat x y))))
    (put 'div '(rational rational) (lambda (x y) (tag (div-rat x y))))
    (put 'equ? '(rational rational)
        (lambda (x y) (and (= (numer x) (numer y))
                           (= (denom x) (denom y)))))
    (put '=zero? '(rational) (lambda (x) (= (numer x) 0)))
    (put 'make 'rational (lambda (n d) (tag (make-rat n d))))
    'done)
(define (make-rational n d)
    ((get 'make 'rational) n d))
(define (numer r) (apply-generic 'numer r))
(define (denom r) (apply-generic 'denom r))

; Recatangular complex number package
(define (install-rectangular-package)
    (define (real-part z) (car z))
    (define (imag-part z) (cdr z))
    (define (make-from-real-imag x y) (cons x y))
    (define (magnitude z) (sqrt (+ (square (real-part z)) (square (imag-part z)))))
    (define (angle z) (atan (imag-part z) (real-part z)))
    (define (make-from-mag-ang r a) (cons (* r (cos a)) (* r (sin a))))

    (define (tag x) (attach-tag 'rectangular x))
    (put 'real-part '(rectangular) real-part)
    (put 'imag-part '(rectangular) imag-part)
    (put 'magnitude '(rectangular) magnitude)
    (put 'angle '(rectangular) angle)
    (put 'equ? '(rectangular rectangular) (lambda (x y) (and (= (real-part x) (real-part y))
                                                 (= (imag-part x) (imag-part y)))))
    (put '=zero? '(rectangular) (lambda (x) (and (= (real-part x) 0)
                                                 (= (imag-part x) 0))))
    (put 'make-from-real-imag 'rectangular (lambda (x y) (tag (make-from-real-imag x y))))
    (put 'make-from-mag-ang 'rectangular (lambda (r a) (tag (make-from-mag-ang r a))))
    'done)

; Polar complex number package
(define (install-polar-package)
    (define (magnitude z) (car z))
    (define (angle z) (cdr z))
    (define (make-from-mag-ang r a) (cons r a))
    (define (real-part z) (* (magnitude z) (cos (angle z))))
    (define (imag-part z) (* (magnitude z) (sin (angle z))))
    (define (make-from-real-imag x y)
        (cons (sqrt (+ (square x) (square y)))
        (atan y x)))

    (define (tag x) (attach-tag 'polar x))
    (put 'real-part '(polar) real-part)
    (put 'imag-part '(polar) imag-part)
    (put 'magnitude '(polar) magnitude)
    (put 'angle '(polar) angle)
    (put 'equ? '(polar polar) (lambda (x y) (and (= (magnitude x) (magnitude y))
                                                 (= (angle x) (angle y)))))
    (put '=zero? '(polar) (lambda (x) (and (= (magnitude x) 0)
                                           (= (angle x) 0))))
    (put 'make-from-real-imag 'polar (lambda (x y) (tag (make-from-real-imag x y))))
    (put 'make-from-mag-ang 'polar (lambda (r a) (tag (make-from-mag-ang r a))))
    'done)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))

(define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))

; Complex number package
(define (install-complex-package)
    (define (make-from-real-imag x y)
        ((get 'make-from-real-imag 'rectangular) x y))
    (define (make-from-mag-ang r a)
        ((get 'make-from-mag-ang 'polar) r a))

    (define (add-complex z1 z2)
        (make-from-real-imag (+ (real-part z1) (real-part z2))
                             (+ (imag-part z1) (imag-part z2))))
    (define (sub-complex z1 z2)
        (make-from-real-imag (- (real-part z1) (real-part z2))
                             (- (imag-part z1) (imag-part z2))))
    (define (mul-complex z1 z2)
        (make-from-mag-ang (* (magnitude z1) (magnitude z2))
                           (+ (angle z1) (angle z2))))
    (define (div-complex z1 z2)
        (make-from-mag-ang (/ (magnitude z1) (magnitude z2))
                           (- (angle z1) (angle z2))))

    (define (tag z) (attach-tag 'complex z))
    (put 'add '(complex complex) (lambda (z1 z2) (tag (add-complex z1 z2))))
    (put 'add3 '(complex complex complex)
        (lambda (z1 z2 z3) (tag (add-complex z1 (add-complex z2 z3)))))
    (put 'sub '(complex complex) (lambda (z1 z2) (tag (sub-complex z1 z2))))
    (put 'mul '(complex complex) (lambda (z1 z2) (tag (mul-complex z1 z2))))
    (put 'div '(complex complex) (lambda (z1 z2) (tag (div-complex z1 z2))))
    (put 'equ? '(complex complex) equ?)
    (put '=zero? '(complex) =zero?)
    (put 'make-from-real-imag 'complex (lambda (x y) (tag (make-from-real-imag x y))))
    (put 'make-from-mag-ang 'complex (lambda (r a) (tag (make-from-mag-ang r a))))

    (put 'real-part '(complex) real-part)
    (put 'imag-part '(complex) imag-part)
    (put 'magnitude '(complex) magnitude)
    (put 'angle '(complex) angle)
    'done)
(define (make-complex-from-real-imag x y)
    ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
    ((get 'make-from-mag-ang 'complex) r a))

(define (apply-generic op . original-args)
    (define (raise-args args)
        (list (raise (raise (raise (car args))))
              (cadr args)
              ; (raise (raise (caddr args))))))
              (raise (raise (raise (caddr args))))))

    (define (apply-generic-iter op arg-number . args)
        (let ((type-tags (map type-tag args)))
            (let ((proc (get op type-tags)))
                 (if proc
                     (apply proc (map contents args))
                     (let ((same-type-args (raise-args args)))
                          (let ((same-type-tags (map type-tag same-type-args)))
                               (let ((same-type-proc (get op same-type-tags)))
                                    (if same-type-proc
                                        (apply same-type-proc (map contents same-type-args))))
                                        (error "Нет функции после преобразований" (list op same-type-tags))))))))
    (apply apply-generic-iter (append (list op 1) original-args)))

(install-integer-package)
(install-real-package)
(install-rational-package)
(install-rectangular-package)
(install-polar-package)
(install-complex-package)

(define (raise x)
    (let ((type (type-tag x)))
         (cond ((equal? type 'integer) (make-rational x 1))
               ((equal? type 'rational) (make-real (/ (numer x) (denom x))))
               ((equal? type 'real) (make-complex-from-real-imag x 0))
               (else x))))

(define (raise x) (apply-generic 'raise x))
(put 'raise '(integer)  (lambda (x) (make-rational x 1)))
(put 'raise '(rational) (lambda (x)
    (make-real (/ (numer (attach-tag 'rational x))
                  (denom (attach-tag 'rational x))))))
(put 'raise '(real) (lambda (x) (make-complex-from-real-imag x 0)))

(add3 1 (make-complex-from-real-imag 2 3) 4)
